name: Notify for Main Release

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  issues: write

env:
  NODE_VERSION: "20"

jobs:
  build-test-notify:
    runs-on: ubuntu-latest
    name: Build, Test and Notify

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Check if PR already exists
        id: check-pr
        run: |
          PR_EXISTS=$(gh pr list --base main --head develop --json number --jq length)
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest commits
        id: commits
        if: steps.check-pr.outputs.pr_exists == '0'
        run: |
          COMMITS=$(git log main..develop --oneline --max-count=5 | sed 's/^/- /')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create issue for manual PR creation
        if: steps.check-pr.outputs.pr_exists == '0'
        run: |
          gh issue create \
            --title "🚀 Ready for Release: develop → main" \
            --body "Build and tests passed on develop branch. Ready to create PR to main.
            
            **Branch:** develop
            **Build status:** ✅ Passed
            **Date:** $(date -u)
            
            ## Recent Changes:
            ${{ steps.commits.outputs.commits }}
            
            To create the PR manually, run:
            \`\`\`bash
            gh pr create --base main --head develop --title '🚀 Release: develop → main' --body 'Release ready for main branch'
            \`\`\`
            
            Or use the GitHub web interface to create a PR from develop to main." \
            --label "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
